### ISSUE TITLE
Minecraft hanging on joining world

### ISSUE THREAD

**Issue by maddie-j** [LordFokas/BlazeMap#12]
Version: 0.5.x (alpha)

Sometimes when joining the world, it will hang on the "Joining world..." screen. Once force closed, the Launcher will return to the screen complaining of being out of memory. This was despite the Minecraft instance being given 16GB RAM via the launcher and HWInfo showing that there was free space both within the instance (delta before and after starting Minecraft <16GB) and also in Physical Memory availability.

After crashing, the log would not be further written to, so there's no error message indicating what triggered the hang.

This seemed to trigger fairly reliably when focusing on a window other than Minecraft between hitting "Play" in the launcher and the main menu appearing. However, I can no longer replicate this as of v0.5.4g. But I did have it hang at least once on this version. It just wouldn't then hang when I went to replicate on purpose to investigate...

TODO:

1. Validate the issue definitely isn't reoccuring
2.  Do memory availability checking before processing map images. If memory available to the instance is lower than some threshold, hold off on processing that chunk/map layer. 

My suspicion from a later crash in a new world is that Blaze Map may be briefly pushing above the memory available while loading new map layers from disk? This is especially suspicious as a lot of the times I was having crashes, it was when I had more virtual memory committed than physical memory available, meaning it would take more work to move things in and out of swap if it briefly needed to load a large number of map layer chunks into memory at the same time.

**Comment by LordFokas** [comment]
Closing this unless someone manages to reproduce it again
