### ISSUE TITLE
Please update to 1.20.1

### ISSUE THREAD

**Issue by liltousin** [LordFokas/BlazeMap#15]
Hi I play on the terrafirmagreg build and I would really like your mod to be able to add to this build

**Comment by LordFokas** [comment]
We're working on it. Please be patient.
Once we release a final version of Blaze Map and Cartography in 1.18.2 we're abandoning that game version and moving on to 1.20.x
If you'd like to discuss this further you're welcome to join us on Discord: https://lordfokas.dev/discord
