### ISSUE TITLE
Game freezing when void is exposed

### ISSUE THREAD

**Issue by Cathal-poon** [LordFokas/BlazeMap#53]
When the void is exposed to skylight the game freezes. 
No error's or exceptions are logged.

When the void is exposed but there's a block above then there's no issue.

When it's a column of only air. Freeze.

Minecraft 1.18.2
Forge 40.2.9
Blaze Map 0.5.16-beta

M1 Mac
MacOS 14.4.1

Prism Launcher 8.3

**Comment by maddie-j** [comment]
@LordFokas I think we fixed this if you wanna close it out?
